name: "hello world"
on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "hello world"
      - name: Print second
        run: echo "message two"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo message
        run: echo "job 2"
